const TERM_RDF = "http://www.w3.org/1999/02/22-rdf-syntax-ns"
const TERM_RDFS = "http://www.w3.org/2000/01/rdf-schema"
const TERM_OWL = "http://www.w3.org/2002/07/owl"
const TERM_XSD = "http://www.w3.org/2001/XMLSchema"

const TERM_RDF_TYPE = "<$TERM_RDF#type>"
const TERM_RDF_REST = "<$TERM_RDF#rest>"
const TERM_RDF_FIRST = "<$TERM_RDF#first>"
const TERM_RDFS_SUB_CLASS_OF = "<$TERM_RDFS#subClassOf>"
const TERM_RDFS_SUB_PROPERTY_OF = "<$TERM_RDFS#subPropertyOf>"
const TERM_RDFS_DATATYPE = "<$TERM_RDFS#Datatype>"
const TERM_RDFS_DOMAIN = "<$TERM_RDFS#domain>"
const TERM_RDFS_RANGE = "<$TERM_RDFS#range>"

const TERM_XSD_BOOLEAN = "<$TERM_XSD#boolean>"

const TERM_OWL_THING = "<$TERM_OWL#Thing>"
const TERM_OWL_CLASS = "<$TERM_OWL#Class>"
const TERM_OWL_ALL_VALUES_FROM = "<$TERM_OWL#allValuesFrom>"
const TERM_OWL_ON_PROPERTY = "<$TERM_OWL#onProperty>"
const TERM_OWL_ON_CLASS = "<$TERM_OWL#onClass>"
const TERM_OWL_ON_DATA_RANGE = "<$TERM_OWL#onDataRange>"
const TERM_OWL_RESTRICTION = "<$TERM_OWL#Restriction>"
const TERM_OWL_SOME_VALUES_FROM = "<$TERM_OWL#someValuesFrom>"
const TERM_OWL_INTERSECTION_OF = "<$TERM_OWL#intersectionOf>"
const TERM_OWL_UNION_OF = "<$TERM_OWL#unionOf>"
const TERM_OWL_ONE_OF = "<$TERM_OWL#oneOf>"
const TERM_OWL_OBJECT_PROPERTY = "<$TERM_OWL#ObjectProperty>"
const TERM_OWL_DATATYPE_PROPERTY = "<$TERM_OWL#DatatypeProperty>"
const TERM_OWL_NAMED_INDIVIDUAL = "<$TERM_OWL#NamedIndividual>"
const TERM_OWL_ANNOTATION_PROPERTY = "<$TERM_OWL#AnnotationProperty>"
const TERM_OWL_COMPLEMENT_OF = "<$TERM_OWL#complementOf>"
const TERM_OWL_DATATYPE_COMPLEMENT_OF = "<$TERM_OWL#datatypeComplementOf>"
const TERM_OWL_HAS_VALUE = "<$TERM_OWL#hasValue>"
const TERM_OWL_HAS_SELF = "<$TERM_OWL#hasSelf>"
const TERM_OWL_MIN_CARDINALITY = "<$TERM_OWL#minCardinality>"
const TERM_OWL_MIN_QUALIFIED_CARDINALITY = "<$TERM_OWL#minQualifiedCardinality>"
const TERM_OWL_MAX_CARDINALITY = "<$TERM_OWL#maxCardinality>"
const TERM_OWL_MAX_QUALIFIED_CARDINALITY = "<$TERM_OWL#maxQualifiedCardinality>"
const TERM_OWL_CARDINALITY = "<$TERM_OWL#cardinality>"
const TERM_OWL_QUALIFIED_CARDINALITY = "<$TERM_OWL#qualifiedCardinality>"
const TERM_OWL_INVERSE_OF = "<$TERM_OWL#inverseOf>"

const TERM_OWL_MEMBERS = "<$TERM_OWL#members>"
const TERM_OWL_DISTINCT_MEMBERS = "<$TERM_OWL#distinctMembers>"

const TERM_OWL_DISJOINT_WITH = "<$TERM_OWL#disjointWith>"
const TERM_OWL_ALL_DISJOINT_CLASSES = "<$TERM_OWL#AllDisjointClasses>"
const TERM_OWL_DISJOINT_UNION_OF = "<$TERM_OWL#disjointUnionOf>"
const TERM_OWL_PROPERTY_DISJOINT_WITH = "<$TERM_OWL#propertyDisjointWith>"
const TERM_OWL_EQUIVALENT_CLASS = "<$TERM_OWL#equivalentClass>"
const TERM_OWL_EQUIVALENT_PROPERTY = "<$TERM_OWL#equivalentProperty>"

const TERM_OWL_PROPERTY_CHAIN_AXIOM = "<$TERM_OWL#propertyChainAxiom>"
const TERM_OWL_HAS_KEY = "<$TERM_OWL#hasKey>"

const TERM_OWL_FUNCTIONAL_PROPERTY = "<$TERM_OWL#FunctionalProperty>"
const TERM_OWL_INVERSE_FUNCTIONAL_PROPERTY = "<$TERM_OWL#InverseFunctionalProperty>"
const TERM_OWL_REFLEXIVE_PROPERTY = "<$TERM_OWL#ReflexiveProperty>"
const TERM_OWL_IRREFLEXIVE_PROPERTY = "<$TERM_OWL#IrreflexiveProperty>"
const TERM_OWL_SYMMETRIC_PROPERTY = "<$TERM_OWL#SymmetricProperty>"
const TERM_OWL_ASYMMETRIC_PROPERTY = "<$TERM_OWL#AsymmetricProperty>"
const TERM_OWL_TRANSITIVE_PROPERTY = "<$TERM_OWL#TransitiveProperty>"

const TERM_OWL_SAME_AS = "<$TERM_OWL#sameAs>"
const TERM_OWL_DIFFERENT_FROM = "<$TERM_OWL#differentFrom>"
const TERM_OWL_ALL_DIFFERENT = "<$TERM_OWL#AllDifferent>"

const TERM_OWL_NEGATIVE_PROPERTY_ASSERTION = "<$TERM_OWL#NegativePropertyAssertion>"
const TERM_OWL_SOURCE_INDIVIDUAL = "<$TERM_OWL#sourceIndividual>"
const TERM_OWL_TARGET_INDIVIDUAL = "<$TERM_OWL#targetIndividual>"
const TERM_OWL_ASSERTION_PROPERTY = "<$TERM_OWL#assertionProperty>"

const TERM_OWL_DEPRECATED_CLASS = "<$TERM_OWL#DeprecatedClass>"
const TERM_OWL_DEPRECATED = "<$TERM_OWL#deprecated>"
const TERM_OWL_DEPRECATED_PROPERTY = "<$TERM_OWL#DeprecatedProperty>"
